//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obs_çalışma
{
    using System;
    using System.Collections.Generic;
    
    public partial class ders_alir
    {
        public string ogrenci_no { get; set; }
        public string ders_kod { get; set; }
        public Nullable<decimal> vize_not { get; set; }
        public Nullable<decimal> final_not { get; set; }
    
        public virtual ders ders { get; set; }
        public virtual ogrenci ogrenci { get; set; }
    }
}
